// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package cortex.api.job.computervision

@SerialVersionUID(0L)
final case class TLModelType(
    `type`: cortex.api.job.computervision.TLModelTypeType = cortex.api.job.computervision.TLModelTypeType.Empty
    )